version: 0.2

env:
  variables:
    ECR_REPO_URI: 226054275210.dkr.ecr.us-west-2.amazonaws.com/images-app
    ECR_REGION: us-west-2

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $ECR_REGION)
      - docker pull $ECR_REPO_URI:latest

  build:
    commands:
      - docker build --cache-from $ECR_REPO_URI:latest --tag $ECR_REPO_URI:latest .
      - DATABASE_ROOT_PASSWORD=$(aws ssm get-parameter --name IMAGES-APP-DB-PASSWORD --with-decryption --query 'Parameter.Value' --output text)
      - sed -i s/SED_REPLACE_DB_PASS/$DATABASE_ROOT_PASSWORD/g Templates/edx-provision-configuration.json

  post_build:
    commands:
      - docker push $ECR_REPO_URI:latest
artifacts:
  files:
    - '**/*'
